name: Default

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nikmarkovicavnet/iotc-mtb-build:02.00
      credentials:
        username: nikmarkovicavnet
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build Package
        run: scripts/build-firmware.sh

      - name: Publish Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware.zip
          path: artifacts/*

